export const ENV_KEYS = {
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  BRAVE_SEARCH_API_KEY: 'BRAVE_SEARCH_API_KEY',
  GOOGLE_GENERATIVE_AI_API_KEY: 'GOOGLE_GENERATIVE_AI_API_KEY',
} as const;
